# Generated by Django 4.2.1 on 2023-06-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcomments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
