# Generated by Django 4.2.1 on 2023-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='friends',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='comments',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_notes',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
