# Generated by Django 4.2.1 on 2023-06-14 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_pcomments_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profiles',
            name='follows',
            field=models.ManyToManyField(blank=True, default=None, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
