# Generated by Django 4.2.1 on 2023-05-23 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profiles_friends_projects_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='project_name',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.projects'),
        ),
    ]
