# Generated by Django 4.2.1 on 2023-05-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_profiles_first_name_profiles_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='friends',
        ),
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_notes',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
