# Generated by Django 4.2.1 on 2023-06-14 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_activities_delete_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='act_creator',
        ),
        migrations.AddField(
            model_name='activities',
            name='ready_by_user',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ready_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activities',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
