# Generated by Django 4.2.1 on 2023-05-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_profiles_friends_profiles_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='location',
            new_name='password',
        ),
    ]
