# Generated by Django 4.2.1 on 2023-06-14 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_remove_activities_act_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='ready_by_user',
            new_name='read_by_user',
        ),
        migrations.AddField(
            model_name='activities',
            name='project_involved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.projects'),
        ),
        migrations.AddField(
            model_name='activities',
            name='user_involved',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_involved', to=settings.AUTH_USER_MODEL),
        ),
    ]
