# Generated by Django 4.2.1 on 2023-05-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profiles_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Pcomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='None', max_length=1000)),
                ('date', models.DateField()),
                ('username', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='home.profiles')),
            ],
        ),
    ]
