# Generated by Django 4.2.1 on 2023-06-14 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_rename_ready_by_user_activities_read_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='read_by_user',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
