# Generated by Django 4.2.1 on 2023-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_profiles_username_pcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tags',
        ),
    ]
