# Generated by Django 4.2.1 on 2023-05-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
    ]
