# Generated by Django 4.2.1 on 2023-05-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_profiles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='p_image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default='None', upload_to='static/images'),
        ),
    ]
