# Generated by Django 4.2.1 on 2023-05-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_projects_p_image_alter_profiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcomments',
            name='username',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
