# Generated by Django 4.2.1 on 2023-05-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_projects_p_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcomments',
            name='pname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.projects'),
        ),
    ]
