# Generated by Django 4.2.1 on 2023-05-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_projects_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='project_link',
        ),
    ]
