# Generated by Django 4.2.1 on 2023-05-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_lovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
