# Generated by Django 4.2.1 on 2023-05-27 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_remove_profiles_likes_projects_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='likes',
        ),
        migrations.AddField(
            model_name='lovers',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
        migrations.AddField(
            model_name='projects',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='p_creator',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
