# Generated by Django 4.2.1 on 2023-05-28 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0025_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='viewed',
            field=models.ManyToManyField(blank=True, default=None, related_name='viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
