# Generated by Django 4.2.1 on 2023-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_featured_creator_alter_featured_project_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
