# Generated by Django 4.2.1 on 2023-05-28 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_projects_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='downloaded',
            field=models.ManyToManyField(blank=True, default=None, related_name='downloaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='tagged',
            field=models.ManyToManyField(blank=True, default=None, related_name='tagged', to=settings.AUTH_USER_MODEL),
        ),
    ]
