# Generated by Django 4.2.1 on 2023-05-28 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0030_projects_downloaded_projects_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_projects',
            name='tagger',
            field=models.ForeignKey(default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
