# Generated by Django 4.2.1 on 2023-05-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_tags_projects_tagger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='curator',
            new_name='favorby',
        ),
    ]
