# Generated by Django 4.2.1 on 2023-05-28 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0032_rename_curator_favourites_favorby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Downloaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloader', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pd_name', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.projects')),
            ],
        ),
    ]
