# Generated by Django 4.2.1 on 2023-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_profiles_image_alter_projects_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='p_image',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
    ]
