# Generated by Django 4.2.1 on 2023-05-30 06:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_projects_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
