# Generated by Django 4.2.1 on 2023-05-30 06:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_profiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='p_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
