# Generated by Django 4.2.1 on 2023-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_projects_p_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='creator',
        ),
        migrations.AddField(
            model_name='profiles',
            name='proj_created',
            field=models.ManyToManyField(blank=True, default=None, related_name='proj_created', to='home.projects'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='p_image',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
    ]
