# Generated by Django 4.2.1 on 2023-06-08 08:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_featured_creator_profiles_proj_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='p_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
